### ISSUE TITLE
InputTextWithHint is broken

### ISSUE THREAD

**Issue by Wolf65** [AllenDang/cimgui-go#184] opened 2023-08-17 18:37 UTC
InputTextWithHint is broken

Tentatively"commit 280ec596116b5bf60a8541169603f7cce7db702b".
works fine

error.log is empty

on the last commit (not implement-imvector) 
crash in my project
```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/AllenDang/cimgui-go.InputTextCallbackData.EventFlag.func2(0xc00029d7b0?)
        S:/goProject/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20230816065634-b5893ac3ee03/cimgui_funcs.go:19717 +0x2c
github.com/AllenDang/cimgui-go.InputTextCallbackData.EventFlag({0xc00029d7b0, 0x40000, 0x40000, 0xc0002a4108, 0x0, 0x0, {0xc0002a4110, 0x3}, 0x2, 0x4, ...})
        S:/goProject/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20230816065634-b5893ac3ee03/cimgui_funcs.go:19717 +0xa5
github.com/AllenDang/cimgui-go.generalInputTextCallback(0x717c5ff650)
        S:/goProject/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20230816065634-b5893ac3ee03/input_text.go:34 +0xf8
github.com/AllenDang/cimgui-go._Cfunc_igInputTextWithHint(0x266f6242a50, 0x266f6242960, 0x266f6242c60, 0x4, 0x40000, 0x7ff6f1da2b00, 0xc0002a4108)
        _cgo_gotypes.go:25593 +0x53
github.com/AllenDang/cimgui-go.InputTextWithHint.func2(0x7ff6f21be5a0?, 0xc0002a3f30?, 0xc0000afa98?, 0x7ff6f1be0bca?, 0x40000, 0xc0000afaa8?)
        S:/goProject/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20230816065634-b5893ac3ee03/input_text.go:79 +0xbb
github.com/AllenDang/cimgui-go.InputTextWithHint({0x7ff6f2221abd?, 0x7ff6f24e1f01?}, {0x7ff6f2221fb6, 0x5}, 0x7ff6f21743d0, 0x0, 0x7ff6f2259bb8)
        S:/goProject/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20230816065634-b5893ac3ee03/input_text.go:79 +0x1df
poehelper/window.pageGeneral()
        S:/goProject/PoEHelper/window/Settings.go:104 +0x45
poehelper/window.SettingsWindow(0xc0?)
        S:/goProject/PoEHelper/window/Settings.go:68 +0x29f
main.loop()
        S:/goProject/PoEHelper/main.go:156 +0x5d
github.com/AllenDang/cimgui-go.loopCallback()
        S:/goProject/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20230816065634-b5893ac3ee03/backend.go:22 +0x3d
github.com/AllenDang/cimgui-go._Cfunc_igRunLoop(0x266ea4646b0, 0x7ff6f1da2870, 0x7ff6f1da28b0, 0x7ff6f1da28f0, 0x7ff6f1da2970)
        _cgo_gotypes.go:27778 +0x4e
github.com/AllenDang/cimgui-go.(*GLFWBackend).Run.func1(0x7ff6f1da2245?)
        S:/goProject/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20230816065634-b5893ac3ee03/glfw_backend.go:98 +0x9f
github.com/AllenDang/cimgui-go.(*GLFWBackend).Run(0xc000122900?, 0x7ff6f22599b8?)
        S:/goProject/pkg/mod/github.com/!allen!dang/cimgui-go@v0.0.0-20230816065634-b5893ac3ee03/glfw_backend.go:98 +0x33
main.main()
        S:/goProject/PoEHelper/main.go:146 +0x356
exit status 2
make: *** [Makefile:9: run] Error 1
```

crash in demo from examples/
```
panic: runtime error: cgo argument has Go pointer to Go pointer

goroutine 1 [running]:
github.com/AllenDang/cimgui-go.InputTextCallbackData.EventFlag.func2(0xc000158240?)
        S:/goProject/cimgui-go/cimgui_funcs.go:19717 +0x2c
github.com/AllenDang/cimgui-go.InputTextCallbackData.EventFlag({0xc000158240, 0x40000, 0x40000, 0xc000152390, 0x0, 0x0, {0xc0001523a0, 0xa}, 0xb, 0xc, ...})
        S:/goProject/cimgui-go/cimgui_funcs.go:19717 +0xa5
github.com/AllenDang/cimgui-go.generalInputTextCallback(0xd1c9dff760)
        S:/goProject/cimgui-go/input_text.go:34 +0xf8
github.com/AllenDang/cimgui-go._Cfunc_igInputTextWithHint(0x2363fa8c4d0, 0x2363fa8ba90, 0x2363fa8ba70, 0xb, 0x40000, 0x7ff79bab95d0, 0xc000152390)
        _cgo_gotypes.go:25593 +0x53
github.com/AllenDang/cimgui-go.InputTextWithHint.func2(0x7ff79be93c80?, 0xc000154820?, 0x2363fa8b5d0?, 0x2363fa8b5d0?, 0x40000, 0x0?)
        S:/goProject/cimgui-go/input_text.go:79 +0xbb
github.com/AllenDang/cimgui-go.InputTextWithHint({0x7ff79bebae4b?, 0x436f000000000002?}, {0x7ff79bebe66a, 0x14}, 0x7ff79be69d60, 0x0, 0x7ff79bec5d40)
        S:/goProject/cimgui-go/input_text.go:79 +0x1df
main.showWidgetsDemo()
        S:/goProject/cimgui-go/examples/main.go:64 +0x23f
main.loop()
        S:/goProject/cimgui-go/examples/main.go:103 +0x17
github.com/AllenDang/cimgui-go.loopCallback()
        S:/goProject/cimgui-go/backend.go:22 +0x3d
github.com/AllenDang/cimgui-go._Cfunc_igRunLoop(0x23613f5d130, 0x7ff79bab9340, 0x7ff79bab9380, 0x7ff79bab93c0, 0x7ff79bab9440)
        _cgo_gotypes.go:27778 +0x4e
github.com/AllenDang/cimgui-go.(*GLFWBackend).Run.func1(0xc000072410?)
        S:/goProject/cimgui-go/glfw_backend.go:98 +0x9f
github.com/AllenDang/cimgui-go.(*GLFWBackend).Run(0xc00007e080?, 0x7ff79bec5d58?)
        S:/goProject/cimgui-go/glfw_backend.go:98 +0x33
main.main()
        S:/goProject/cimgui-go/examples/main.go:139 +0x21d
exit status 2
```

**Comment by Wolf65** [comment] 2023-08-23 04:17
PR https://github.com/AllenDang/cimgui-go/pull/187 fix problem

**Comment by gucio321** [comment] 2023-08-23 09:23
Cool

**Comment by Wolf65** [comment] 2023-08-26 16:58
@gucio321 I don't understand anything on commit 022a31c244c16b4c277df236733960bbdf07a99b
imgui.InputTextWithHint is not working for some reason.

**Comment by gucio321** [comment] 2023-08-26 17:54
@Wolf65 can't reproduce tbh. `imgui.InputTextWithHint` is part of example and example works fine.
Could you please post some demo code?

**Comment by gucio321** [comment] 2023-08-26 17:55
well, I've just tried to edit text in input text item and, well, Now I can see the crash

**Comment by gucio321** [comment] 2023-08-26 18:34
_I suppose_ that I know whats wrong.
I've decided to use go function `new` to allocate new struct pointer, but it _might_ be a mistake

**Comment by gucio321** [comment] 2023-08-26 20:42
I'm going to do some basic debugging right now and think about fix later (e.g. tomorrow)
- It looks like panic is raised somewhere in  (*InputTextCallbackData).handle
- dlv says that it occures in some type of defer to this function (but not in defer call from code but from some runtime defers?)
- I suppose FieldUserData since it is of type unsafe.Pointer and its the real cause of this panic.

context:
converting from C is as follows:
```go
	result.FieldUserData = unsafe.Pointer(cvalue.UserData)
```

and back to C:
```go
	FieldUserData := self.FieldUserData
	
	result.UserData = (FieldUserData)
```

so it becomes unsafe.Pointer and doesn't get back to its previous stage.

**Comment by gucio321** [comment] 2023-08-26 20:44
in `glfw_backend.h` there is a
```h
typedef void (*VoidCallback)();
```
so I think we need to use it there

**Comment by gucio321** [comment] 2023-08-27 09:44
I hope it is a solution: https://stackoverflow.com/questions/38031401/how-can-i-fill-out-void-c-pointer-in-go

**Comment by gucio321** [comment] 2023-08-27 16:16
here is some important documentation: https://pkg.go.dev/cmd/cgo#hdr-Passing_pointers
it says:
> The runtime/cgo.Handle type can be used to safely pass Go values between Go and C. See the runtime/cgo package documentation for details.

and go doc cgo.Handle says:
```console
    Some C functions accept a void* argument that points to an arbitrary data
    value supplied by the caller. It is not safe to coerce a cgo.Handle (an
    integer) to a Go unsafe.Pointer, but instead we can pass the address of
    the cgo.Handle to the void* parameter, as in this variant of the previous
    example:

        package main

        /*
        extern void MyGoPrint(void *context);
        static inline void myprint(void *context) {
            MyGoPrint(context);
        }
        */
        import "C"
        import (
        	"runtime/cgo"
        	"unsafe"
        )

        //export MyGoPrint
        func MyGoPrint(context unsafe.Pointer) {
        	h := *(*cgo.Handle)(context)
        	val := h.Value().(string)
        	println(val)
        	h.Delete()
        }

        func main() {
        	val := "hello Go"
        	h := cgo.NewHandle(val)
        	C.myprint(unsafe.Pointer(&h))
        	// Output: hello Go
        }
```

**Comment by gucio321** [comment] 2023-08-28 15:53
teporary solution is to build with `GODEBUG=cgocheck=0`

**Comment by gucio321** [comment] 2023-08-29 06:51
I managed to fix this single case (GetEventFlags) by using runtime.pinner.
I will try to implement this mechanism in generator

**Comment by gucio321** [comment] 2023-08-31 07:22
- Blocked by https://github.com/golang/go/issues/62356
Unfortunately can't find any better solution for now

**Comment by gucio321** [comment] 2023-09-03 06:30
Workaround: disable void* return type in generator

And one more thing:
It doesn't happen when passing an unsafe pointer created in go to c. The problem appears when getting pointer from c and passing it back

**Comment by gucio321** [comment] 2023-09-03 10:42
@Wolf65 I've applied downgrade - it should work now.

**Comment by gucio321** [comment] 2023-09-10 07:04
There is a go PR already 🎉
- https://github.com/golang/go/pull/62549

**Comment by gucio321** [comment] 2023-09-13 19:28
good news! GO PR has been merged. Waiting for go release

**Closed** 2023-09-14 09:51 UTC
Labels: enhancement, frozen
