### ISSUE TITLE
Cannot call imgui.CurrentIO().SetIniFilename

### ISSUE THREAD

**Issue by neclepsio** [AllenDang/cimgui-go#87] opened 2023-01-13 09:16 UTC
`SetIniFilename` is a method of `*IO`, while `CurrentIO()` returns `IO`.
This is not true for `IniFileName`, which is a method of `IO` even if it has almost the same signature.

    ImGuiIO_SetIniFilename(ImGuiIO *ImGuiIOPtr, const char* v)
    ImGuiIO_GetIniFilename(ImGuiIO *self)

become:

    func (self *IO) SetIniFilename(v string)
    func (self IO) IniFilename() string

**Comment by pztrn** [comment] 2023-01-13 17:32
Dirty workaround until generation will be fixed:

```go
	ioRaw := imgui.CurrentIO()
	io := &ioRaw
	io.SetIniFilename()
```

**Comment by gucio321** [comment] 2023-01-13 18:31
I think that every method should have pointer receiver whether or not it needs it.

**Comment by gucio321** [comment] 2023-01-13 18:44
well, so the situation is as follows:
CurrentIO has `returnTypeType` "returnTypeStruct", so maybe we should just convert it into `*struct` for all the types?

**Comment by gucio321** [comment] 2023-01-13 19:54
@neclepsio @pztrn try #88, it should work

**Comment by pztrn** [comment] 2023-02-15 17:15
I have to re-raise this issue as problem as of 84cf33bf89a2 isn't fixed.

Consider this code:

```go
	guiConfigPath := mw.app.DataPath("imgui.ini")
	imguiIO.SetIniFilename(guiConfigPath)

	log.Printf("GUI path: %s (imgui: %s), savings rate: %.2f)\n", guiConfigPath, imguiIO.IniFilename(), imguiIO.IniSavingRate())
```

Log output:

```
2023/02/15 22:11:43 GUI path: /path/to/config/imgui.ini (imgui: h{!X), savings rate: 5.00)
```

With my advice above:

```go
	guiConfigPath := mw.app.DataPath("imgui.ini")
	iniIO := &imguiIO
	iniIO.SetIniFilename(guiConfigPath)

	log.Printf("GUI path: %s (imgui: %s), savings rate: %.2f)\n", guiConfigPath, imguiIO.IniFilename(), imguiIO.IniSavingRate())
```

Log output:

```
2023/02/15 22:12:53 GUI path: /path/to/config/imgui.ini (imgui: hkxC), savings rate: 5.00)
```

`iniIO.IniFilename()` is empty. `/path/to/config` is generated properly with `mw.app.DataPath()`.

**Comment by pztrn** [comment] 2023-04-23 10:30
Hey, any updates on that?

I've already apply crutches for saving window sizes and positions, yet it is impossible (at least I found no way) to save docking data manually.

**Comment by gucio321** [comment] 2023-04-24 16:34
@pztrn I'm sorry but I think I had to miss something - I'm reading thread above and can't see the exact faulty code.

Could you please briefly describe an issue once again along with reproducable code?

**Comment by pztrn** [comment] 2023-04-25 09:25
See https://github.com/AllenDang/cimgui-go/issues/87#issuecomment-1431716067. Still same. While I definitely sets valid path in imgui, imgui itself reports corrupted file name and writes configuration in CWD/PWD in randomly named file or didn't write config file at all.

**Comment by neclepsio** [comment] 2023-04-25 09:48
If I remember correctly, in imgui the argument to SetIniFilename is not
copied, but stored. The Go wrapper converts the string, passes it to
cimgui, than frees it: that's the problem. It should not be freed until the
next call, or maybe you should allocate a static buffer and never free it,
and Go SetIniFilename should copy to it.

**Comment by gucio321** [comment] 2023-08-22 19:10
@neclepsio @Wolf65 @pztrn  could you check #118 I suppose it might have fixed this issue

**Comment by Wolf65** [comment] 2023-08-23 04:22
unfortunately the problem still remains by default the ini file name is empty when using imgui.CurrentIO().SetIniFilename the name changes constantly and if it saves it is a garbage name from memory.
![image](https://github.com/AllenDang/cimgui-go/assets/9079150/ab890e80-ab74-4be2-973e-89368f5e0804)

**Comment by gucio321** [comment] 2023-08-30 20:01
okey, I have literally no idea why this might be broken
(Set)IniFilename are functions generated by our codegen, so something have to be fixed there?
The only thing I have on top of my mind is that this string is freed too early but the pointer (for some reason) isn't so it doesn't panic but prints random meory?

**Comment by ptxmac** [comment] 2023-08-30 20:04
Take a look at #91, there's an explaination of what the problem is

**Comment by gucio321** [comment] 2023-08-30 20:13
```go
func (self IO) SetIniFilename(v string) {
        vArg, vFin := WrapString(v)
 
        selfArg, selfFin := self.handle()
        defer selfFin()
        C.wrap_ImGuiIO_SetIniFilename(selfArg, vArg)

        vFin()
}
```

ok, this looks strange in my opinion. 

take a look on this:
```go
package main

/*
#include <stdlib.h>
typedef struct {
	char* x;
} info;

void setX(info* self, char* y) {
	self->x = y;
}

char* getX(info* self) {
	return self->x;
}
*/
import "C"

import (
	"fmt"
	"unsafe"
)

func main() {
	x := "hello GO"
	info := new(C.info)
	xArg, xFin := WrapString(x)
	C.setX(info, xArg)
	fmt.Println(C.GoString(C.getX(info)))
	xFin()
	fmt.Println(C.GoString(C.getX(info)))
}

func WrapString(value string) (wrapped *C.char, finisher func()) {
	wrapped = C.CString(value)
	finisher = func() { C.free(unsafe.Pointer(wrapped)) } // nolint: gas
	return
}
```
it behaves EXACTLY the same

**Comment by gucio321** [comment] 2023-08-30 20:23
ok, so we hit some really important issue - using finalizers in our library.

## what are finalizers?
As i undrstand they are these functions in `defer` clause that are in every function.
They are intended to cleanup allocated memory to save it

## When MUST we NOT use  finalizers?
- on arguments to Set* funcs (like here)
- on `self` arguments in other functions
- generally on every POINTER we pass to C and we're going to leave it there on runtime

## when should we use them?
- on temporary data passed to C like FontConfig in AddFontFromMemory
- on everything that we create especially for C and we don't need it later (in C form)

**Comment by neclepsio** [comment] 2023-08-30 20:37
The problem is lays here: SetIniFilename does not copy the string, just
store the pointer in imgui. So you create a C pointer, set the inifilename
pointer in imgui to it, than free it, and the reference points to freed
memory. I tried to explain this before.

**Comment by ptxmac** [comment] 2023-08-30 20:41
Yeah, as mentioned in the other issue, `C.wrap_ImGuiIO_SetIniFilename` is not actually a function in Imgur - it's just a function that assigns a value to a struct. That means the caller is responsible for keeping the memory alive

**Comment by neclepsio** [comment] 2023-08-30 20:42
So, I think you should allocate a string for IniFilename in the wrapper, call cimgui SetIniFilename just once, than go SetIniFilename should modify that single string you allocated (or reallocate and call cimgui SetIniFilename if allocation size does not suffice).

**Comment by Wolf65** [comment] 2023-08-31 04:22
A temporary solution in glfw_backend.cpp stack `io->IniFilename = "";` replace with `io->IniFilename = "imgui.ini";`(line 117) and this allows imgui to write and read the .ini file

**Comment by Wolf65** [comment] 2023-08-31 04:31
Imho. It seems that the glfw_backend.cpp file is suspicious and differs from the file in imgui examples. And it causes problems with "only event update". It won't fix setIniFilename but it should help with default behavior.

**Comment by Wolf65** [comment] 2023-08-31 15:48
@gucio321 Maybe create a separate general issue on this problem.

In my opinion glfw_backend.cpp should be deleted io->IniFilename = ""; .After deletion imgui.ini is created by default changes are written and after restart settings are restored. And this behavior is preferable since SetIniFilename is less important than no imgui.ini at all.

**Comment by gucio321** [comment] 2023-09-03 10:16
I'm going to take a look on this and try to solve the root cause of this.

**Comment by gucio321** [comment] 2023-09-03 10:18
btw you can always use fixed code before it is merged to master by running
```sh
go mod edit -replace github.com/AllenDang/cimgui-go=github.com/wolf65/cimgui-go@e58f05d7ae603a10e312e2e29f900d29ca0b1558
go mod tidy
```

**Closed** 2023-09-07 05:56 UTC
Labels: bug
