### ISSUE TITLE
imgui.ini has random names

### ISSUE THREAD

**Issue by Wolf65** [AllenDang/cimgui-go#164] opened 2023-06-16 16:13 UTC
The .ini file is not created after startup. If I use imgui.CurrentIO().SetIniFilename("imgui.ini"), files are created with the name of any of the imgui.text and it keeps changing (if you look through the metric)

**Comment by neclepsio** [comment] 2023-08-01 06:41
Duplicate of #87

**Closed** 2023-08-22 19:11 UTC
Labels: duplicate
