### ISSUE TITLE
Memory is used after C.free call at SetIniFilename

### ISSUE THREAD

**Issue by WinPooh32** [AllenDang/cimgui-go#91] opened 2023-01-15 14:50 UTC
``` go
func wrapString(value string) (wrapped *C.char, finisher func()) {
	wrapped = C.CString(value)
	finisher = func() { C.free(unsafe.Pointer(wrapped)) } // nolint: gas
	return
}

func (self IO) SetIniFilename(v string) {
	vArg, vFin := wrapString(v)
	defer vFin()

	C.wrap_ImGuiIO_SetIniFilename(self.handle(), vArg)
}
```

imgui internally stores pointer to the string and uses it when required, but it happens after C.free was called from GO wrapper. 

Can be reproduced with this code:
```
...
	window = imgui.CreateGlfwWindow("Hello from cimgui-go", 1200, 900, 0)

	context := imgui.CurrentContext()

	io := imgui.CurrentIO()
	io.SetIniFilename("imgui.ini")
	
	window.Run(loop)
```

**Comment by ptxmac** [comment] 2023-05-09 15:59
I'm also hitting this issue. Especially because of the built-in backend which sets the IniFilename to "" when it's initialized, so effective disabling ini file, and it's impossible to enable it again because of this bug.

The `SetIniFilename` is generated from a struct field, not a function call.  I don't think it's ever safe to free any memory given to a struct in this way - imgui doesn't have a chance to copy value.

Either strings should never be freed when we're setting fields, or the c-wrappers should copy the strings...
Of course that means the string will be leaked, unless we first release the previous string when setting a new

**Comment by neclepsio** [comment] 2023-08-01 06:42
Duplicate of #87

**Comment by gucio321** [comment] 2023-09-03 12:55
closing as duplicate, because main discussion is on the other issue

**Closed by gucio321** 2023-09-03 12:55 UTC
Labels: investigating
